package ru.d3rvich.domain.model

enum class Category(val code: String, val text: String) {
    AnyCategory("any", "Any Category"),
    GeneralKnowledge("9", "General Knowledge"),
    EntertainmentBooks("10", "Entertainment: Books"),
    EntertainmentFilm("11", "Entertainment: Film"),
    EntertainmentMusic("12", "Entertainment: Music"),
    EntertainmentMusicalsTheatres("13", "Entertainment: Musicals & Theatres"),
    EntertainmentTelevision("14", "Entertainment: Television"),
    EntertainmentVideoGames("15", "Entertainment: Video Games"),
    EntertainmentBoardGames("16", "Entertainment: Board Games"),
    ScienceNature("17", "Science & Nature"),
    ScienceComputers("18", "Science: Computers"),
    ScienceMathematics("19", "Science: Mathematics"),
    Mythology("20", "Mythology"),
    Sports("21", "Sports"),
    Geography("22", "Geography"),
    History("23", "History"),
    Politics("24", "Politics"),
    Art("25", "Art"),
    Celebrities("26", "Celebrities"),
    Animals("27", "Animals"),
    Vehicles("28", "Vehicles"),
    EntertainmentComics("29", "Entertainment: Comics"),
    ScienceGadgets("30", "Science: Gadgets"),
    EntertainmentJapaneseAnimeManga("31", "Entertainment: Japanese Anime & Manga"),
    EntertainmentCartoonAnimations("32", "Entertainment: Cartoon & Animations"),
}